[package]
name = "eyern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
dfdx = "0.10.0"
ndarray = "0.15.6"
ndarray-npy = "0.8.1"
